### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [brucetoo/ActivityAnimation#1]

**Comment by brucetoo** [comment]
https://gist.github.com/brucetoo/f7c9bcabe2ce51610ccf
this gist will show u.More detail see 
https://github.com/brucetoo/ActivityAnimation/blob/master/app/src/main/java/com/brucetoo/activityanimation/ViewPagerFragment.java

**Comment by vbauer** [comment]
Hmm.. I don't see there any information about license.

**Comment by brucetoo** [comment]
Thank u any way.Here 
https://github.com/brucetoo/ActivityAnimation/commit/220119961045b09b452e82e1b923350dc45e0766

**Comment by vbauer** [comment]
Thank you for information.
