### ISSUE TITLE
图片放大后连边界都看不到了

### ISSUE THREAD

**Issue by eling13** [brucetoo/ActivityAnimation#2]
如题。pager里的第一张图越放大，只能显示到中间的，如果想查看图片的左边界区域，怎么整？
就是在pager里第一张图，和最后一张图出现这样的情况。

**Comment by brucetoo** [comment]
你拖动就可以显示边界啊,怎么会看不到

**Comment by eling13** [comment]
你试试，第一张图放大后拖动时就就把viewpager拖动了

**Comment by brucetoo** [comment]
你是不是在图片左边加了什么VIew? 想实现什么?还是说你要在viewpager中间加个 padding 什么的？

**Comment by eling13** [comment]
没有。我就是直接测试你的demo。

**Comment by eling13** [comment]
你没发现第一张图和最后一张图放大后只要触发了viewpaget的滑动就出现这样的问题了

**Comment by brucetoo** [comment]
其实问题不大吧,你水平滚动的事件被viewpager监听了 而且这并不是第一张和最后一张才有吧....

**Comment by eling13** [comment]
。。。我只能说第一张和最后一张只要放大后触发，然后我想看放大后的边界呢，根本就滚动不过去吧

**Comment by eling13** [comment]
其他的都能在放大后滚动查看全貌，就第一张和最后一张触碰到整个viewpager边界时出现这样的问题

**Comment by brucetoo** [comment]
好的 我有时间看下

**Comment by brucetoo** [comment]
用最新的代码,解决了这个

**Comment by TonyTangAndroid** [comment]
我刚刚测试发现最新的代码，这个问题还是存在。点击第一张图片，放大它，往左 滑动的时候，正常应该这个图片的内容往左滑动，但是没有。

**Comment by brucetoo** [comment]
viewPager是用普通的？

**Comment by TonyTangAndroid** [comment]
是的。没有做任何自定义。但是就是第一张和最后一张有这个问题。

**Comment by brucetoo** [comment]
demo中我忘了更新代码.用的不是普通的ViewPager，你应该使用的 ReboundViewPager 这个在剪裁的时候有问题. 我马上更新demo代码.你试试吧
