### ISSUE TITLE
第一张和最后一张图片放大后有问题

### ISSUE THREAD

**Issue by saky0542** [brucetoo/ActivityAnimation#3]

**Comment by brucetoo** [comment]
什么问题?

**Comment by saky0542** [comment]
这个效果还是不错的，给你点赞，就是之前那个人提出的，第一个图和最后一个图放大后边界不见了，因为你现在的代码里面有9张图，如果只有一张的图的话，问题就明显了，还有一个就是请教一下，我现在是viewpager+三个fragment，如果把你这个集成进去的话，会出现一个问题，就是点击图片进入到你的fragment之后，再返回，viewpager的另外两个fragment会变成空白的。

**Comment by saky0542** [comment]
另外我在你这个基础上做一些超长图片和超宽图片（超过硬件解码，长或者宽大于4096的图片）的处理，希望能得到你的一些建议

**Comment by brucetoo** [comment]
发现问题了,你改下不同的scaleType看看 。我空了看下这个...至于你说viewpager+三个fragment 你是怎么集成的，最好能提供个demo 我看看..或者你找到的解决方案  希望提交下代码

**Comment by brucetoo** [comment]
或者说你可以试试把viewpagerfragment继承至Dialogfragment来实现，应该就不会行为add 或者replace影响到viewpager里……有时间我改下这个

**Comment by brucetoo** [comment]
用最新的代码,解决了这个
