### ISSUE TITLE
当imgUrl比例和thumbnailimgUrl比例不一样

### ISSUE THREAD

**Issue by dengcb** [brucetoo/ActivityAnimation#5]
就会有问题，弹出时效果不对。
比如原图是16:9，缩略图是1:1。

**Comment by brucetoo** [comment]
略缩图需要自己弄啊...而不是用我写的那个.

**Comment by dengcb** [comment]
是的啊，我用我自己的原图和缩略图。
原图是网友自己传的，各种比例都有，缩略图我自己定死的是16:9的横向图。
然后当原图也是16:9的时候，效果就是正常的。
当原图比例是1:1甚至9:16的时候，弹出效果就完全不对了。

我还有一个地方所有缩略图都是1:1，还没尝试，按之前的测试应该也不行。
我看了demo的原图和缩略图，比例是一样的。
如果我把全站图片都重新生成一个比例一样的缩略图工作量很大啊。

**Comment by dengcb** [comment]
我目前解决方案是，原图和缩略图用同一张图，就没毛病了。
但是如果原图尺寸很大的时候，有点浪费带宽。

**Comment by brucetoo** [comment]
其实你可以考虑在所有的图下载完成后都按照16:9或者一个固定的比例format一次...

**Comment by brucetoo** [comment]
其实现在就是用的原图和缩略图都是同一张图片,不过微信应该是分开的,他们应该是有获取不同图的接口吧...不过如果在外面能下载完图,点击后的图就会复用下载完成的(当然这是图片加载库里面做好的)

**Comment by dengcb** [comment]
我服务器上有九个目录存放不同用途的缩略图，各种比例和大小。还有一个存原始尺寸的。

我看demo里，先下载缩略图显示，点击后下载原图，缓存本地。
然后用原图实现弹出效果。
但是弹出的时候貌似计算尺寸和位置没用缩略图的，用的原图的，所以缩略图就出问题了。
我用原图代替缩略图，然后centerCrop属性会让原图按缩略图的比例显示。
然后弹出就会用原图的尺寸位置来执行就视觉正确了。
不知道我理解的对不对，其实缩略图派上用场了，就是计算时没用比例不一样的缩略图呢？

**Comment by dengcb** [comment]
不知道你有没有时间做一个测试，原图放一个9:16的竖图，缩略图用1:1的小图。

**Comment by brucetoo** [comment]
请忽略demo中略缩图的逻辑..你能给个小的demo? 我抽时间看看..其实如果要加上略缩图,逻辑应该会要增加在点击预览的时候判断是否有缓存全图,如果有全图缓存就执行缩放逻辑，如果没有就要先显示略缩图然后等待全图下载完成.现在微信就是这么做的吧

**Comment by dengcb** [comment]
是的，第一次下载原图时，会先居中显示缩略图，原图下载好了就缩放至原图。
微信的逻辑是这样。
第二页艾求详情会用到你的代码，第三页艾特详情还没用。

**Comment by brucetoo** [comment]
刚看了下 直接用原图是可以的呢 设置 centerCrop效果更佳 ...如果实在要做极致优化 提供你们不同比例图片地址给我,我写个demo试试 BTW:app奔溃率有点高...

**Comment by dengcb** [comment]
抱歉，bug太多了。测试图片如下
`imgList.add(0, "http://cdn.at.cn/upload/146336617940.jpg");
imgList.add(1, "http://cdn.at.cn/upload/146540079128.jpg");
imgList.add(2, "http://cdn.at.cn/upload/146528287960.jpg");
imgList.add(3, "http://cdn.at.cn/upload/146271377052.jpg");
imgList.add(4, "http://cdn.at.cn/upload/146502027460.jpg");
imgList.add(5, "http://cdn.at.cn/upload/146296005117.jpg");
imgList.add(6, "http://cdn.at.cn/upload/146386101517.jpg");
imgList.add(7, "http://cdn.at.cn/upload/146289180072.jpg");
imgList.add(8, "http://cdn.at.cn/upload/146378563799.jpg");`

然后缩略图是：
`url = imgUrl.replace("upload/", "upload/w/")`

**Comment by brucetoo** [comment]
现在是想做微信的效果?

**Comment by dengcb** [comment]
微信效果最好了。
最起码要用上缩略图，保证缩略图和原图比例不同不会影响弹出效果。
这样才实用。

**Comment by brucetoo** [comment]
现在你给的图片 我这边不会影响弹出效果呢。。要加上略缩图的使用其实只需要再 ImageBrowseFragment的布局中加上 一个photoView 来显示略缩图，然后通过判断是否有全图缓存来 确定

``` java
   if (position == pos && ImageLoader.getInstance().getDiskCache().get(imageUrls.get(pos)) != null) {//only animate when position equals u click in pre layout
                    photoView.animateFrom(imageInfo);
                }
```

不同的imageInfo就可以了吧  只是需要多考虑一个imageInfo而已。

**Comment by dengcb** [comment]
你把动画放慢10倍试试，有时候一闪而过看不清楚。
现在是本地缓存了全图了，弹出也是错误的。

**Comment by dengcb** [comment]
其实有没有微信第一次缩略图显示缩放功能没关系，只求缓存完原图后，从缩略图点击弹出展示原图没毛病就非常好了。

**Comment by brucetoo** [comment]
发现解决方案了  等我试着改下.

**Comment by dengcb** [comment]
好的：）谢谢！

**Comment by brucetoo** [comment]
朋友,我觉得你还是用 getThumbnailImageUrl 这个方法来获取略缩图吧(将返回同比例的图)... 想将不同比例的图片做出缩放的效果...我刚试着改了 至少暂时没发现很好的解决方案....我感觉微信的比例也是一样的。

**Comment by dengcb** [comment]
能不能点击缩略图，取回原图，然后用原图做缩放呢？
这样比如展示10次，只有一次点击的话，会节约9次的带宽。

**Comment by brucetoo** [comment]
这个可以有 我晚上有时间加下. 略缩图的问题你就用我的那个方法,能获取到同比例的图片

**Comment by dengcb** [comment]
好的，请你试试，拜谢！

**Comment by brucetoo** [comment]
微信的效果done：https://github.com/brucetoo/ImageBrowse/commit/83a600e94714ecbd0fe5d11cd789d89e255f5b3c

**Comment by dengcb** [comment]
赞！我更新了下代码，确实如微信效果了。
想要顺畅缩放，需要等比例缩略图，这个我打算全站重新生成一次。
发现一个小小bug：多张图片，打开其中一张，滑动几张后，再滑回第一张打开的图片，会有闪动。

**Comment by brucetoo** [comment]
会有闪动是指?  其实用我那个获取略缩图的方法也行

**Comment by dengcb** [comment]
闪动就是指从缩略图到全图的动画又会播放一次。
126.net提供的缩略图，万一哪天流量太大给我封了，我就傻眼了。

**Comment by brucetoo** [comment]
大概知道了 应该有一个变量来判断是否已经执行过动画.
那倒也是，比较那是用于我司各个产品的.

**Comment by dengcb** [comment]
☺自己公司的产品没问题
而且这个迟早都要改，早点动手没错的。
谢谢！如果有修复我再更新代码

**Comment by brucetoo** [comment]
没事哦..我过会儿或者晚上有时间改下这个..你们图片加载也是用的 [Android-Universal-Image-Loader](https://github.com/nostra13/Android-Universal-Image-Loader) ?

**Comment by dengcb** [comment]
是的，用的universal-image-loader，只是比较奇怪，用了gridview加载图片后，图片渐现动画就没了，我在你demo里测试没问题，我再看看代码。
